### ISSUE TITLE
replace_code_newstyle broken on v1.10

### ISSUE THREAD

**Issue by vtjnash** [FluxML/IRTools.jl#108]
JuliaLang/julia#49113 now requires the nargs to be passed as the length of the slotnames array, and does not accept an extra argument here anymore: https://github.com/FluxML/IRTools.jl/blob/62d5f4295f58fd543464d300e81d3b4a50256cb6/src/reflection/utils.jl#L131-L134

**Comment by maleadt** [comment]
Fixed by https://github.com/FluxML/IRTools.jl/pull/109
